Add jupyter_bokeh requirement
in Fault101 course -> Fault 1_1 Lab:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/IPython/core/formatters.py:1036, in MimeBundleFormatter.__call__(self, obj, include, exclude)
   1033     method = get_real_method(obj, self.print_method)
   1035     if method is not None:
-> 1036         return method(include=include, exclude=exclude)
   1037     return None
   1038 else:

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/holoviews/core/dimension.py:1275, in Dimensioned._repr_mimebundle_(self, include, exclude)
   1268 def _repr_mimebundle_(self, include=None, exclude=None):
   1269     """
   1270     Resolves the class hierarchy for the class rendering the
   1271     object using any display hooks registered on Store.display
   1272     hooks.  The output of all registered display_hooks is then
   1273     combined and returned.
   1274     """
-> 1275     return Store.render(self)

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/holoviews/core/options.py:1423, in Store.render(cls, obj)
   1421 data, metadata = {}, {}
   1422 for hook in hooks:
-> 1423     ret = hook(obj)
   1424     if ret is None:
   1425         continue

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/holoviews/ipython/display_hooks.py:287, in pprint_display(obj)
    285 if not ip.display_formatter.formatters['text/plain'].pprint:
    286     return None
--> 287 return display(obj, raw_output=True)

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/holoviews/ipython/display_hooks.py:261, in display(obj, raw_output, **kwargs)
    259 elif isinstance(obj, (HoloMap, DynamicMap)):
    260     with option_state(obj):
--> 261         output = map_display(obj)
    262 elif isinstance(obj, Plot):
    263     output = render(obj)

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/holoviews/ipython/display_hooks.py:149, in display_hook.<locals>.wrapped(element)
    147 try:
    148     max_frames = OutputSettings.options['max_frames']
--> 149     mimebundle = fn(element, max_frames=max_frames)
    150     if mimebundle is None:
    151         return {}, {}

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/holoviews/ipython/display_hooks.py:209, in map_display(vmap, max_frames)
    206     max_frame_warning(max_frames)
    207     return None
--> 209 return render(vmap)

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/holoviews/ipython/display_hooks.py:76, in render(obj, **kwargs)
     73 if renderer.fig == 'pdf':
     74     renderer = renderer.instance(fig='png')
---> 76 return renderer.components(obj, **kwargs)

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/holoviews/plotting/renderer.py:397, in Renderer.components(self, obj, fmt, comm, **kwargs)
    395 if embed or config.comms == 'default':
    396     return self._render_panel(plot, embed, comm)
--> 397 return self._render_ipywidget(plot)

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/holoviews/plotting/renderer.py:419, in Renderer._render_ipywidget(self, plot)
    417 def _render_ipywidget(self, plot):
    418     # Handle rendering object as ipywidget
--> 419     widget = ipywidget(plot, combine_events=True)
    420     if hasattr(widget, '_repr_mimebundle_'):
    421         return widget._repr_mimebundle_(), {}

File ~/Workspace/chipwhisperer/.venv/lib/python3.12/site-packages/panel/io/notebook.py:558, in ipywidget(obj, doc, **kwargs)
    539 def ipywidget(obj: Any, doc=None, **kwargs: Any):
    540     """
    541     Returns an ipywidget model which renders the Panel object.
    542
   (...)
    556     Returns an ipywidget model which renders the Panel object.
    557     """
--> 558     from jupyter_bokeh.widgets import BokehModel
    560     from ..pane import panel
    561     doc = doc if doc else Document()

ModuleNotFoundError: No module named 'jupyter_bokeh'